import Head from 'next/head'
// import { Inter } from '@next/font/google'
import Banner from 'components/Banner'
import Image from 'next/image'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const handleOnBannerBtnClick = () => {
    console.log('Banner button clicked')
  }
  return (
    <div className='mb-56 sm:px-4 md:px-10'>
      <Head>
        <title>Coffee Connosieur</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='mt-10 mx-auto max-w-6xl px-4 sm:mt-12 sm:mx-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28'>
        <Banner
          buttonText='View stores nearby'
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className='absolute top-0 z-10 md:right-[20%]'>
          <Image
            src='/static/hero-image.png'
            alt='hero rimage'
            width={700}
            height={400}
          />
        </div>
      </main>

      {/* <footer className={styles.footer}></footer>/s */}
    </div>
  )
}
